;
; File generated by cc65 v 2.17 - Git N/A
;
	.fopt		compiler,"cc65 v 2.17 - Git N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_tgi_static_stddrv
	.import		_tgi_install
	.import		_tgi_uninstall
	.import		_tgi_init
	.import		_tgi_clear
	.import		_tgi_setcolor
	.import		_tgi_setpalette
	.import		_tgi_getmaxx
	.import		_tgi_getmaxy
	.import		_tgi_line
	.export		_X
	.export		_main

.segment	"RODATA"

_Palette:
	.byte	$01
	.byte	$00

.segment	"BSS"

_maxX:
	.res	2,$00
_maxY:
	.res	2,$00
_X:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(_tgi_static_stddrv)
	ldx     #>(_tgi_static_stddrv)
	jsr     _tgi_install
	jsr     _tgi_init
	jsr     _tgi_getmaxx
	sta     _maxX
	stx     _maxX+1
	jsr     _tgi_getmaxy
	sta     _maxY
	stx     _maxY+1
	lda     #<(_Palette)
	ldx     #>(_Palette)
	jsr     _tgi_setpalette
	lda     #$02
	jsr     _tgi_setcolor
	jsr     _tgi_clear
	lda     #$00
	sta     _X
	sta     _X+1
L0016:	lda     _X
	sec
	sbc     _maxY
	sta     tmp1
	lda     _X+1
	sbc     _maxY+1
	ora     tmp1
	bcc     L0019
	jne     L0017
L0019:	jsr     push0
	jsr     push0
	lda     _maxY
	ldx     _maxY+1
	jsr     pushax
	lda     _X
	ldx     _X+1
	jsr     _tgi_line
	jsr     push0
	jsr     push0
	lda     _X
	ldx     _X+1
	jsr     pushax
	lda     _maxY
	ldx     _maxY+1
	jsr     _tgi_line
	lda     _maxY
	ldx     _maxY+1
	jsr     pushax
	lda     _maxY
	ldx     _maxY+1
	jsr     pushax
	jsr     push0
	lda     _maxY
	sec
	sbc     _X
	pha
	lda     _maxY+1
	sbc     _X+1
	tax
	pla
	jsr     _tgi_line
	lda     _maxY
	ldx     _maxY+1
	jsr     pushax
	lda     _maxY
	ldx     _maxY+1
	jsr     pushax
	lda     _maxY
	sec
	sbc     _X
	pha
	lda     _maxY+1
	sbc     _X+1
	tax
	pla
	jsr     pushax
	ldx     #$00
	txa
	jsr     _tgi_line
	lda     #$0A
	clc
	adc     _X
	sta     _X
	jcc     L0016
	inc     _X+1
	jmp     L0016
L0017:	jsr     _tgi_uninstall
	ldx     #$00
	txa
	rts

.endproc

